spring.main.web-application-type=none
logging.level.org.springframework.ai=debug
spring.ai.minimax.chat.base-url=https://api.minimaxi.chat/
spring.ai.minimax.chat.options.model=DeepSeek-R1
#spring.ai.minimax.api-key=